# -*- coding: utf-8 -*-
"""
QGISGeoServerLayerLoader
A QGIS plugin that simplifies publishing and managing geospatial data on GeoServer.
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/

This script initializes the plugin, making it known to QGIS.
"""

__version__ = '0.9.2'

# Define the plugin name here
__plugin_name__ = 'Q2G - QGIS to GeoServer Connector'

# Save the plugin package name for proper module unloading
import sys
__plugin_package__ = __name__

# Ensure the plugin package is properly registered in sys.modules
if __name__ not in sys.modules:
    sys.modules[__name__] = sys.modules[__plugin_package__]

def classFactory(iface):
    """Load QGISGeoServerLayerLoader class from main.py.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .main import QGISGeoServerLayerLoader
    return QGISGeoServerLayerLoader(iface)